#!/bin/bash

DOWNLOAD_PATH=./tmp
APPID=cb-energietransitie
COURSE=et-remote
COURSE_PATH=$DOWNLOAD_PATH/${COURSE}

cd questionnaire
python build.py
cd -

cp -r coursebuilder/assets/* $COURSE_PATH/files/assets/
cp -r coursebuilder/views/* $COURSE_PATH/files/views/

cp questionnaire/build/*css $COURSE_PATH/files/assets/css/
cp questionnaire/build/*js $COURSE_PATH/files/assets/js/
cp questionnaire/build/*js $COURSE_PATH/files/assets/lib/
cp questionnaire/lib/*html $COURSE_PATH/files/assets/lib/

cd $COURSE_PATH
zip -r ${COURSE}.zip *
cd -

source activate
#python coursebuilder/import.py upload course / $APPID $APPID.appspot.com --force_overwrite --archive_path $COURSE_PATH/${COURSE}.zip
#python coursebuilder/import.py upload course /energietransitie_marta $APPID $APPID.appspot.com --force_overwrite --archive_path $COURSE_PATH/${COURSE}.zip
python coursebuilder/import.py upload course / $APPID $APPID.appspot.com --force_overwrite --archive_path $COURSE_PATH/${COURSE}.zip
